name: Formatting Check

on:
  pull_request:

env:
  GITHUB_PULL_REQUEST_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  GITHUB_PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}

jobs:
  format:
    name: Run formatting tasks
    runs-on: ubuntu-latest
    steps:
      #------------------------------------------------------------
      - uses: actions/checkout@v4
      #------------------------------------------------------------
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      #------------------------------------------------------------
      - name: â© CI Install â©
        run: npm ci
      #------------------------------------------------------------
      - name: ðŸ“‹ Install ðŸ“‹
        run: npm install
      #------------------------------------------------------------
      - name: ðŸŒˆ Lint ðŸŒˆ
        run: echo "not implemented yet"
      #------------------------------------------------------------
      - name: ðŸ“‹ Check for changes ðŸ“‹
        run: |
          git --no-pager diff
          git diff --exit-code --quiet || {
            echo "There are changes to commit"
            exit 1
          }
      #------------------------------------------------------------
      - name: ðŸ“¢ Formatting needs to be updated. See message below. ðŸ“¢
        if: ${{ failure() }}
        run: |
          echo "### Formatting failed." >> $GITHUB_STEP_SUMMARY
          echo "âž¤ execute âž¤" >> $GITHUB_STEP_SUMMARY
          echo "```shell" >> $GITHUB_STEP_SUMMARY
          echo "run npm lint:fix" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
      #------------------------------------------------------------
